<?php
/**
 * Includo – Web Accessibility Audit Tool
 * Install Wizard
 *
 * Author: Franco Aquini – Web Salad
 * License: MIT
 */

declare(strict_types=1);

ini_set('display_errors', '1');
error_reporting(E_ALL);

$rootDir = realpath(__DIR__ . '/..') ?: (__DIR__ . '/..');
$configFile = $rootDir . '/config.local.php';
$lockFile = __DIR__ . '/install.lock';

function h(string $s): string { return htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }

// Disable installer if already installed (strong protection)
if (file_exists($configFile)) {
  http_response_code(403);
  echo "<h1>Installer disabled</h1><p><strong>Includo is already installed.</strong></p>";
  echo "<p>For security, delete or protect the <code>/install</code> folder.</p>";
  exit;
}

if (file_exists($lockFile)) {
  http_response_code(403);
  echo "<h1>Installation locked</h1>";
  echo "<p>Delete <code>install/install.lock</code> only if you really need to reinstall.</p>";
  exit;
}

function env_checks(string $rootDir): array {
  $checks = [];
  $checks[] = ['PHP >= 8.0', version_compare(PHP_VERSION, '8.0.0', '>='), PHP_VERSION];
  foreach (['curl','dom','json','mbstring','pdo','pdo_mysql'] as $ext) {
    $checks[] = ["Extension: $ext", extension_loaded($ext), extension_loaded($ext)?'loaded':'missing'];
  }
  $dirs = [$rootDir.'/reports', $rootDir.'/logs'];
  foreach ($dirs as $d) {
    if (!is_dir($d)) @mkdir($d, 0755, true);
    $checks[] = ['Writable: '.str_replace($rootDir,'',$d), is_writable($d), $d];
  }
  return $checks;
}

function write_config_local(string $rootDir, array $data): bool {
  $cfg = "<?php\n/**\n * Includo – local configuration\n * Generated by installer on ".date('c')."\n */\n\n";
  $cfg .= "define('DB_HOST', ".var_export($data['db_host'], true).");\n";
  $cfg .= "define('DB_NAME', ".var_export($data['db_name'], true).");\n";
  $cfg .= "define('DB_USER', ".var_export($data['db_user'], true).");\n";
  $cfg .= "define('DB_PASS', ".var_export($data['db_pass'], true).");\n";
  $cfg .= "define('DB_CHARSET', 'utf8mb4');\n\n";
  $cfg .= "define('WCAG_VERSION', '2.2');\n";
  $cfg .= "define('INCLUDO_STATEMENT_ORG_NAME', ".var_export($data['org_name'], true).");\n";
  $cfg .= "define('INCLUDO_STATEMENT_CONTACT_EMAIL', ".var_export($data['contact_email'], true).");\n";
  $cfg .= "define('INCLUDO_LANG', ".var_export($data['lang'], true).");\n";
  return (bool)file_put_contents($rootDir.'/config.local.php', $cfg, LOCK_EX);
}

$step = isset($_GET['step']) ? max(1,(int)$_GET['step']) : 1;
$msg = '';

if ($_SERVER['REQUEST_METHOD']==='POST') {
  if (($_POST['action'] ?? '') === 'save') {
    $data = [
      'db_host' => trim((string)($_POST['db_host'] ?? 'localhost')),
      'db_name' => trim((string)($_POST['db_name'] ?? 'includo')),
      'db_user' => trim((string)($_POST['db_user'] ?? 'root')),
      'db_pass' => (string)($_POST['db_pass'] ?? ''),
      'org_name' => trim((string)($_POST['org_name'] ?? '')),
      'contact_email' => trim((string)($_POST['contact_email'] ?? '')),
      'lang' => trim((string)($_POST['lang'] ?? 'it')),
    ];
    if (!write_config_local($rootDir, $data)) {
      $msg = "Could not write <code>config.local.php</code>. Check permissions.";
      $step = 2;
    } else {
      file_put_contents($lockFile, "Installed: ".date('c')."\n");
      header('Location: ?step=3');
      exit;
    }
  }
}

$checks = env_checks($rootDir);
$allOk = true;
foreach ($checks as $c) {
    if (empty($c[1])) { // oppure $c['ok'] se usi array associativi
        $allOk = false;
        break;
    }
}
?><!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Includo – Install</title>
<style>
body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Arial,sans-serif;margin:0;background:#f6f7fb;color:#111}
.wrap{max-width:980px;margin:0 auto;padding:24px}
.card{background:#fff;border-radius:16px;box-shadow:0 8px 30px rgba(0,0,0,.06);padding:20px;margin:14px 0}
.badge{display:inline-block;padding:6px 10px;border-radius:999px;background:#eef2ff;font-size:12px}
.btn{display:inline-block;padding:10px 14px;border-radius:12px;border:0;background:#111;color:#fff;text-decoration:none;cursor:pointer;font-weight:700}
.btn.secondary{background:#fff;color:#111;border:1px solid #ddd}
table{width:100%;border-collapse:collapse}
td{padding:8px 10px;border-bottom:1px solid #eee;font-size:14px}
.muted{color:#666;font-size:13px}
.alert{padding:10px 12px;border-radius:12px;background:#fff4e5;border:1px solid #ffd8a8}
.includo-danger{display:flex;gap:16px;padding:18px;border-radius:18px;border:2px solid #c62828;background:linear-gradient(90deg,#ffebee,#fff);box-shadow:0 10px 35px rgba(198,40,40,.18);margin:16px 0}
.includo-danger__icon{width:48px;height:48px;border-radius:14px;display:flex;align-items:center;justify-content:center;background:#c62828;color:#fff;font-size:22px}
.includo-danger__steps{display:grid;gap:8px;margin:10px 0 6px}
.includo-danger__step{background:#fff;border:1px solid #f3b3b3;border-radius:14px;padding:10px 12px}
code{background:#f1f3f6;padding:2px 6px;border-radius:8px}
</style>
</head>
<body>
<div class="wrap">
  <div class="card">
    <div class="badge">Install Wizard</div>
    <h1 style="margin:8px 0 6px">Includo</h1>
    <p class="muted">WCAG 2.2 (A/AA) & European Accessibility Act (EU 2019/882)</p>
  </div>

  <?php if ($msg): ?><div class="card"><div class="alert"><?php echo $msg; ?></div></div><?php endif; ?>

  <?php if ($step===1): ?>
    <div class="card">
      <h2>1) Environment checks</h2>
      <table>
        <?php foreach ($checks as $c): ?>
          <tr><td style="width:48%"><?php echo h($c[0]); ?></td><td style="width:12%"><?php echo $c[1]?'✅':'❌'; ?></td><td class="muted"><?php echo h((string)$c[2]); ?></td></tr>
        <?php endforeach; ?>
      </table>
      <p style="margin-top:14px"><a class="btn" href="?step=2">Continue</a></p>
    </div>

  <?php elseif ($step===2): ?>
    <div class="card">
      <h2>2) Configuration</h2>
      <p class="muted">This will create <code>config.local.php</code> in the project root.</p>
      <form method="post">
        <input type="hidden" name="action" value="save">
        <label>DB Host</label><input name="db_host" value="localhost" style="width:100%;padding:10px 12px;border-radius:12px;border:1px solid #ddd">
        <label>DB Name</label><input name="db_name" value="includo" style="width:100%;padding:10px 12px;border-radius:12px;border:1px solid #ddd">
        <label>DB User</label><input name="db_user" value="" style="width:100%;padding:10px 12px;border-radius:12px;border:1px solid #ddd">
        <label>DB Password</label><input name="db_pass" type="password" value="" style="width:100%;padding:10px 12px;border-radius:12px;border:1px solid #ddd">
        <label>Organisation name (statement)</label><input name="org_name" value="" style="width:100%;padding:10px 12px;border-radius:12px;border:1px solid #ddd">
        <label>Contact email (statement)</label><input name="contact_email" value="" style="width:100%;padding:10px 12px;border-radius:12px;border:1px solid #ddd">
        <label>Language</label>
        <select name="lang" style="width:100%;padding:10px 12px;border-radius:12px;border:1px solid #ddd">
          <option value="it">Italian</option>
          <option value="en">English</option>
        </select>
        <p style="margin-top:14px">
          <button class="btn" type="submit">Save & Finish</button>
          <a class="btn secondary" href="?step=1">Back</a>
        </p>
      </form>
    </div>

  <?php else: ?>
    <div class="card">
      <h2>3) Finished</h2>

      <div class="includo-danger" role="alert" aria-live="assertive">
        <div class="includo-danger__icon" aria-hidden="true">⚠️</div>
        <div>
          <h3 style="margin:0 0 6px">Security action required</h3>
          <p style="margin:8px 0">
            <strong>Delete the <code>/install</code> folder now.</strong><br>
            Leaving it online can allow someone to re-run the installer and compromise this installation.
          </p>
          <div class="includo-danger__steps">
            <div class="includo-danger__step"><strong>1)</strong> Open your hosting File Manager / FTP</div>
            <div class="includo-danger__step"><strong>2)</strong> Delete: <code>/install</code></div>
            <div class="includo-danger__step"><strong>3)</strong> If you cannot delete it, block access (Apache/Nginx rule)</div>
          </div>
          <p class="muted">After deletion, trying to open <code>/install</code> should return <strong>404</strong> or <strong>403</strong>.</p>
        </div>
      </div>

      <p><a class="btn" href="../includo.php">Go to Includo</a></p>
    </div>
  <?php endif; ?>

  <div class="card"><p class="muted">Includo – Author: Franco Aquini – Web Salad · License: MIT</p></div>
</div>
</body></html>
